#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := foo2

EXTRA_COMPONENT_DIRS += $(PROJECT_PATH)/../ESP32Components/
include $(IDF_PATH)/make/project.mk

